name : deep_learning_m1
channels:
  - conda-forge
  - apple
dependencies:
  - graphviz=6.0.2
  - jupyter=1.0.0
  - matplotlib=3.6.2
  - numpy=1.23.2
  - pandas=1.5.2
  - pydot=1.4.2
  - python=3.10.8
  - tensorflow-deps
  - tensorflow-deps=2.10.0
  - pip=22.3.1
  - pip:
    - tensorflow-macos==2.10.0
    - tensorflow-metal==0.6.0
